import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Section } from "~/components/section";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Eduardo Aparicio Cardenes Website</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-5xl py-11 text-center font-extrabold tracking-tight sm:text-[5rem]">
        Eduardo Aparicio Cardenes Website
      </h1>
      <section>
        <div className="container mx-auto text-white py-11">
            <div className="mb-12 text-center">
              <h2 className="text-5xl font-bold text-gray-100">
                My background
              </h2>
            </div>
            <p className="text-center">
              Since I started with my engineer in computer science. I&apos;m
              always been curious about many subjects in specific all of things
              related as Artificial Intelligence until I discovered the web
              technologies that allow you to become real any ideas or business.
            </p>
            <p className="pb-4 pt-4 text-center">
              A whole life of passion for software developments (creations,
              projects, dreams, hobbies, hackathons, ...), It was hard to
              summarize in a four pages CV as usual is required.
            </p>
            <p className="pb-4 text-center">
              I decided to group it in these three main categories
            </p>
            <div className="inline-grid grid-cols-3 gap-4 md:gap-6">
              <Link href="/frontend-developer" className="mt-4">
                <Image
                  src="/images/frontend-developer.png"
                  alt="frontend developer"
                />
                <span>Frontend developer</span>
              </Link>
              <Link href="/software-architect">
                <Image
                  src="/images/software-architect.png"
                  alt="software architect"
                />
                <span>Software Architect</span>
              </Link>
              <Link href="/backend-developer" className="mt-4">
                <Image
                  src="/images/backend-developer.png"
                  alt="backend developer"
                />
                <span>Backend developer</span>
              </Link>
            </div>
        </div>
      </section>
      <Section
        title="some of my projects"
        imageUrl="/images/code-projects-done.jpg"
        reverse
        className="custom-background-color"
      >
        <p className="text">
          As part of this project that try to catch new employers and clients
          attention to open the door to new work opportunities.
        </p>
        <p className="text">
          I upload all{" "}
          <a href="<?=$codeProjectsLink?>">
            my projects here that include hackathons, work and personal ideas
          </a>
        </p>
        <p className="text">Please self yourself to enter and take a look</p>
      </Section>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
        <Link
          className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
          href="https://create.t3.gg/en/usage/first-steps"
          target="_blank"
        >
          <h3 className="text-2xl font-bold">First Steps →</h3>
          <div className="text-lg">
            Just the basics - Everything you need to know to set up your
            database and authentication.
          </div>
        </Link>
        <Link
          className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
          href="https://create.t3.gg/en/introduction"
          target="_blank"
        >
          <h3 className="text-2xl font-bold">Documentation →</h3>
          <div className="text-lg">
            Learn more about Create T3 App, the libraries it uses, and how to
            deploy it.
          </div>
        </Link>
      </div>
      <div className="flex flex-col items-center gap-2">
        <p className="text-2xl text-white">
          {hello.data ? hello.data.greeting : "Loading tRPC query..."}
        </p>
      </div>
    </>
  );
}
